org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx512m
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.daemon.enabled=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
