ext.flutter = [
    compileSdkVersion: 36,
    minSdkVersion: 24,
    targetSdkVersion: 36,
    ndkVersion: "25.1.8937393"
]

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
